/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.limo520.graalvmdemo;

import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.ENGLISH);
        List<Locale> list = List.of(Locale.ENGLISH, Locale.US, Locale.UK, Locale.CHINESE, Locale.SIMPLIFIED_CHINESE);
        for (Locale locale : list) {
            System.out.println("==========" + locale);
            ResourceBundle bundle = ResourceBundle.getBundle("testresource", locale);
            bundle.getKeys().asIterator().forEachRemaining(k -> {
                String value = bundle.getString(k);
                System.out.printf("%s=%s\n", k, value);
            });
            System.out.println();
        }
    }
}
